db.janusgraph {
  storage.cql.cluster-name = hive
  index.search {
    backend = elasticsearch
    hostname = ["elasticsearch"]
  }
}

notification.notifier.webhook.default {
  url = "http://attense-app:8010/internal/webhook/hive"
}

notification.notifier.active = ["webhook"]

cortex {
  servers = [
    {
      name = "cortex"
      url = "http://cortex:9001"
      key = "attense-cortex-key"
    }
  ]
}

