-- =========================================================
-- ATTENSE PostgreSQL Schema
-- =========================================================
-- Canonical PostgreSQL schema for ATTENSE runtime data.
-- This version uses PostgreSQL syntax and adds a first-pass role/permission
-- model so access rules can live alongside the data model.
-- =========================================================

CREATE SCHEMA IF NOT EXISTS attense;
SET search_path TO attense;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- =========================================================
-- Roles and permissions
-- =========================================================
DO $$
BEGIN
    CREATE TYPE user_role AS ENUM (
        'ciso',
        'soc_manager',
        'soc_l1',
        'soc_l2',
        'red_team'
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS "RolePermission" (
    role_name      user_role   NOT NULL,
    permission_key text        NOT NULL,
    description    text        NOT NULL,
    enabled        boolean     NOT NULL DEFAULT true,
    PRIMARY KEY (role_name, permission_key)
);

INSERT INTO "RolePermission" (role_name, permission_key, description) VALUES
    ('ciso',        'view_all_companies',   'View every company and room in the platform'),
    ('ciso',        'view_all_reports',     'Review all generated reports'),
    ('ciso',        'manage_permissions',   'Grant and revoke role permissions'),
    ('soc_manager', 'create_rooms',         'Create and manage Blue Team rooms'),
    ('soc_manager', 'start_blue_team',      'Launch the Blue Team exercise'),
    ('soc_manager', 'manage_hive_keys',     'Provision or rotate TheHive credentials'),
    ('soc_manager', 'investigate_alerts',   'Investigate incoming alerts'),
    ('soc_manager', 'confirm_incidents',    'Confirm alerts as incidents'),
    ('soc_manager', 'start_containment',    'Begin containment actions'),
    ('soc_manager', 'complete_containment', 'Finalize containment actions'),
    ('soc_manager', 'review_reports',       'Review incident and AI reports'),
    ('soc_l1',      'investigate_alerts',   'Investigate incoming alerts'),
    ('soc_l1',      'confirm_incidents',    'Confirm alerts as incidents'),
    ('soc_l1',      'start_containment',    'Begin containment actions'),
    ('soc_l2',      'complete_containment', 'Finalize containment actions'),
    ('soc_l2',      'review_reports',       'Review incident and AI reports'),
    ('red_team',    'join_rooms',           'Join red team rooms'),
    ('red_team',    'create_attacks',       'Launch attack scenarios')
ON CONFLICT DO NOTHING;
-- =========================================================
-- Admin
-- =========================================================
CREATE TABLE IF NOT EXISTS "Admin" (
    admin_name      varchar(50) PRIMARY KEY,
    hashed_password varchar(255) NOT NULL
);

-- =========================================================
-- Company
-- =========================================================
CREATE TABLE IF NOT EXISTS "Company" (
    company_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       varchar(100) NOT NULL UNIQUE,
    status     varchar(30) NOT NULL DEFAULT 'pending',
    created_by varchar(100)
);

-- =========================================================
-- User
-- =========================================================
CREATE TABLE IF NOT EXISTS "User" (
    user_id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        varchar(100) NOT NULL UNIQUE,
    email           varchar(255) NOT NULL UNIQUE,
    hashed_password varchar(255) NOT NULL,
    company_id      integer,
    admin_name      varchar(50)  NOT NULL DEFAULT 'Admin',
    role            user_role    NOT NULL,
    user_type       varchar(30),
    active_room_id  varchar(100),
    CONSTRAINT fk_user_company FOREIGN KEY (company_id) REFERENCES "Company"(company_id),
    CONSTRAINT fk_user_admin   FOREIGN KEY (admin_name)  REFERENCES "Admin"(admin_name),
    CONSTRAINT ck_user_email   CHECK (position('@' in email) > 1),
    CONSTRAINT ck_red_team_type CHECK (role <> 'red_team' OR user_type IN ('expert', 'intermediate')),
    CONSTRAINT ck_user_company_for_role CHECK (
        (role = 'ciso' AND company_id IS NULL)
        OR
        (role <> 'ciso' AND company_id IS NOT NULL)
    )
);

-- =========================================================
-- Red Team profile
-- =========================================================
CREATE TABLE IF NOT EXISTS "RedTeam" (
    user_id    integer PRIMARY KEY,
    zap_api_key bytea,
    CONSTRAINT fk_red_team_user FOREIGN KEY (user_id) REFERENCES "User"(user_id)
        ON DELETE CASCADE
);

-- =========================================================
-- Blue Team profile
-- =========================================================
CREATE TABLE IF NOT EXISTS "BlueTeam" (
    user_id       integer PRIMARY KEY,
    team_role     user_role NOT NULL,
    thehive_api_key bytea,
    cortex_api_key  bytea,
    CONSTRAINT fk_blue_team_user FOREIGN KEY (user_id) REFERENCES "User"(user_id)
        ON DELETE CASCADE,
    CONSTRAINT ck_blue_team_role CHECK (team_role IN ('soc_manager', 'soc_l1', 'soc_l2'))
);

-- =========================================================
-- Room
-- =========================================================
CREATE TABLE IF NOT EXISTS "Room" (
    room_id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_time   timestamptz,
    end_time     timestamptz,
    status       varchar(50),
    user_id      integer NOT NULL,
    CONSTRAINT fk_room_user FOREIGN KEY (user_id) REFERENCES "User"(user_id)
);

-- =========================================================
-- Participated In
-- =========================================================
CREATE TABLE IF NOT EXISTS "ParticipatedIn" (
    room_id integer NOT NULL,
    blue_id integer NOT NULL,
    red_id  integer NOT NULL,
    PRIMARY KEY (room_id, blue_id, red_id),
    CONSTRAINT fk_pi_room FOREIGN KEY (room_id) REFERENCES "Room"(room_id) ON DELETE CASCADE,
    CONSTRAINT fk_pi_blue FOREIGN KEY (blue_id) REFERENCES "BlueTeam"(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_pi_red  FOREIGN KEY (red_id)  REFERENCES "RedTeam"(user_id) ON DELETE CASCADE
);

-- =========================================================
-- Scenario
-- =========================================================
CREATE TABLE IF NOT EXISTS "Scenario" (
    scenario_id  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar(80) NOT NULL,
    description  varchar(250),
    difficulty   varchar(30),
    attack_plan  varchar(250),
    admin_name   varchar(50) NOT NULL,
    CONSTRAINT fk_scenario_admin FOREIGN KEY (admin_name) REFERENCES "Admin"(admin_name)
);

-- =========================================================
-- Incident
-- =========================================================
CREATE TABLE IF NOT EXISTS "Incident" (
    incident_id  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        varchar(80),
    description  varchar(250),
    room_id      integer NOT NULL,
    CONSTRAINT fk_incident_room FOREIGN KEY (room_id) REFERENCES "Room"(room_id) ON DELETE CASCADE
);

-- =========================================================
-- Zero Day Attack
-- =========================================================
CREATE TABLE IF NOT EXISTS "ZeroDayAttack" (
    zero_day_id     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            varchar(80),
    description     varchar(250),
    severity        varchar(30),
    discovery_date  date
);

-- =========================================================
-- Red Team Action
-- =========================================================
CREATE TABLE IF NOT EXISTS "RedTeamAction" (
    action_id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    technique    varchar(100) NOT NULL,
    action_time  timestamptz NOT NULL DEFAULT now(),
    json_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    zero_day_id   integer NOT NULL,
    room_id       integer NOT NULL,
    CONSTRAINT fk_rta_zero_day FOREIGN KEY (zero_day_id) REFERENCES "ZeroDayAttack"(zero_day_id),
    CONSTRAINT fk_rta_room     FOREIGN KEY (room_id) REFERENCES "Room"(room_id) ON DELETE CASCADE
);

-- =========================================================
-- Blue Team Action
-- =========================================================
CREATE TABLE IF NOT EXISTS "BlueTeamAction" (
    action_id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_name   varchar(100) NOT NULL,
    action_time  timestamptz NOT NULL DEFAULT now(),
    json_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    zero_day_id   integer NOT NULL,
    room_id       integer NOT NULL,
    CONSTRAINT fk_bta_zero_day FOREIGN KEY (zero_day_id) REFERENCES "ZeroDayAttack"(zero_day_id),
    CONSTRAINT fk_bta_room     FOREIGN KEY (room_id) REFERENCES "Room"(room_id) ON DELETE CASCADE
);

-- =========================================================
-- AI Report
-- =========================================================
CREATE TABLE IF NOT EXISTS "AIReport" (
    report_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    score     integer,
    ttd       integer,
    ttc       integer,
    summary   varchar(250),
    room_id   integer NOT NULL,
    CONSTRAINT fk_ai_report_room FOREIGN KEY (room_id) REFERENCES "Room"(room_id) ON DELETE CASCADE
);

-- =========================================================
-- Seed data
-- =========================================================
INSERT INTO "Admin" (admin_name, hashed_password)
VALUES ('Admin', 'dev-placeholder-hash-change-before-use')
ON CONFLICT DO NOTHING;
